name: Selenium Tests

on:
  push:
    branches:
      - master  
  pull_request:
    branches:
      - master

jobs:
  selenium-test:
    runs-on: ubuntu-latest 
    services:
      - name: selenium/standalone-chrome:latest 
        options: --shm-size=2g  
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'  
      - name: Install dependencies
        run: |
          mvn clean install  
      - name: Run Selenium tests
      run: |
        ./mvnw test -Dtest=**/seleniumTest/*.java
