name: Run Selenium Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  

    - name: Set up Maven
      uses: marcofranssen/setup-maven@v1  
      with:
        maven-version: '3.8.4'
    
    - name: Install dependencies
      run: mvn install

    - name: Run Selenium tests
      run: mvn test -Dtest=**/seleniumTest/*.java
